### ISSUE TITLE
Client crash on exit

### ISSUE THREAD

**Issue by lmoureaux** [longturn/freeciv21#106]
Start the client and exit without doing anything else.
```
Thread 1 "freeciv-qt" received signal SIGSEGV, Segmentation fault.
0x000055555566482a in QList<QPair<void (*)(void*), update_queue_data*> >::node_copy(QList<QPair<void (*)(void*), update_queue_data*> >::Node*, QList<QPair<void (*)(void*), update_queue_data*> >::Node*, QList<QPair<void (*)(void*), update_queue_data*> >::Node*) ()
(gdb) bt
#0  0x000055555566482a in QList<QPair<void (*)(void*), update_queue_data*> >::node_copy(QList<QPair<void (*)(void*), update_queue_data*> >::Node*, QList<QPair<void (*)(void*), update_queue_data*> >::Node*, QList<QPair<void (*)(void*), update_queue_data*> >::Node*) ()
#1  0x0000555555664783 in QList<QPair<void (*)(void*), update_queue_data*> >::detach_helper(int) ()
#2  0x0000555555663fbc in QList<QPair<void (*)(void*), update_queue_data*> >::detach_helper() ()
#3  0x00005555556632f5 in QList<QPair<void (*)(void*), update_queue_data*> >::detach() ()
#4  0x00005555556642c6 in QList<QPair<void (*)(void*), update_queue_data*> >::begin() ()
#5  0x0000555555663664 in QList<QPair<void (*)(void*), update_queue_data*> >::first() ()
#6  0x0000555555662b47 in QList<QPair<void (*)(void*), update_queue_data*> >::takeFirst() ()
#7  0x0000555555662342 in QQueue<QPair<void (*)(void*), update_queue_data*> >::dequeue() ()
#8  0x0000555555660dc1 in update_queue_free() ()
#9  0x00005555555cfa43 in at_exit() ()
#10 0x00007ffff63e2db7 in __run_exit_handlers () from /usr/lib/libc.so.6
#11 0x00007ffff63e2f5e in exit () from /usr/lib/libc.so.6
#12 0x00005555555d3859 in client_exit() ()
#13 0x00005555555d280b in client_main(int, char**) ()
#14 0x00005555556c3f39 in main ()
```

**Comment by lmoureaux** [comment]
Fixed in 696f454454e8b21dbe582aba0392ca29b901823e
