### ISSUE TITLE
Closing Units list when city view is open causes a client crash when closing the city view

### ISSUE THREAD

**Issue by daavko** [longturn/freeciv21#1119]
**Describe the bug**
If the Units list is closed when a city view is open, it crashes a client when exiting the city view

**To Reproduce**
1. Open the Units list
2. Open a city view
3. Click on the Units button once (to close it "behind the scenes")
4. Close the city view
5. Crash!

**Expected behavior**
I expect the client not to crash

**Platform and version (please complete the following information):**
 - OS: Windows 10
 - Freeciv21 version: beta 2
 - Ruleset/Longturn game (if applicable): not applicable

**Additional context**
No additional context. I'll try to get a stack trace, but it's a hassle on Windows

**Comment by daavko** [comment]
Backtrace from gdb (from current master - 4c6aee6):
```
Thread 1 received signal SIGSEGV, Segmentation fault.
0x00007fff94555ac8 in QWidget::show() () from C:\Projects\freeciv21-origin\build\Windows-x86_64\_CPack_Packages\Windows-x86_64\NSIS\Freeciv21-v3.0.313006-Windows-x86_64\freeciv21\qt5widgets.dll
(gdb) bt
#0  0x00007fff94555ac8 in QWidget::show() () from C:\Projects\freeciv21-origin\build\Windows-x86_64\_CPack_Packages\Windows-x86_64\NSIS\Freeciv21-v3.0.313006-Windows-x86_64\freeciv21\qt5widgets.dll
#1  0x00007ff6dcea1311 in map_view::show_all_fcwidgets (this=0x2021dfc5a00) at C:/Projects/freeciv21-origin/client/mapview.cpp:190
#2  0x00007ff6dce23c2b in city_dialog::hideEvent (this=0x2021e0194e0, event=0x77ff7fa860) at C:/Projects/freeciv21-origin/client/citydlg.cpp:1538
#3  0x00007fff945566e0 in QWidget::event(QEvent*) () from C:\Projects\freeciv21-origin\build\Windows-x86_64\_CPack_Packages\Windows-x86_64\NSIS\Freeciv21-v3.0.313006-Windows-x86_64\freeciv21\qt5widgets.dll
#4  0x00007fff94517ec3 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from C:\Projects\freeciv21-origin\build\Windows-x86_64\_CPack_Packages\Windows-x86_64\NSIS\Freeciv21-v3.0.313006-Windows-x86_64\freeciv21\qt5widgets.dll
#5  0x00007fff95896798 in QCoreApplication::sendEvent(QObject*, QEvent*) () from C:\Projects\freeciv21-origin\build\Windows-x86_64\_CPack_Packages\Windows-x86_64\NSIS\Freeciv21-v3.0.313006-Windows-x86_64\freeciv21\qt5core.dll
#6  0x00007fff9455260a in QWidgetPrivate::hide_helper() () from C:\Projects\freeciv21-origin\build\Windows-x86_64\_CPack_Packages\Windows-x86_64\NSIS\Freeciv21-v3.0.313006-Windows-x86_64\freeciv21\qt5widgets.dll
#7  0x00007fff94556408 in QWidgetPrivate::setVisible(bool) () from C:\Projects\freeciv21-origin\build\Windows-x86_64\_CPack_Packages\Windows-x86_64\NSIS\Freeciv21-v3.0.313006-Windows-x86_64\freeciv21\qt5widgets.dll
#8  0x00007ff6dd1e8aa9 in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (QWidget::*)()>::call(void (QWidget::*)(), QWidget*, void**) (f=(void (QWidget::*)(QWidget * const)) 0x7fff94541000 <QWidget::hide()>, o=0x2021e0194e0, arg=0x77ff7fab90) at C:/msys64/mingw64/include/QtCore/qobjectdefs_impl.h:152
#9  0x00007ff6dd1f38dc in QtPrivate::FunctionPointer<void (QWidget::*)()>::call<QtPrivate::List<>, void>(void (QWidget::*)(), QWidget*, void**) (f=(void (QWidget::*)(QWidget * const)) 0x7fff94541000 <QWidget::hide()>, o=0x2021e0194e0, arg=0x77ff7fab90) at C:/msys64/mingw64/include/QtCore/qobjectdefs_impl.h:185
#10 0x00007ff6dd1f041a in QtPrivate::QSlotObject<void (QWidget::*)(), QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) (which=1, this_=0x2021e1b6050, r=0x2021e0194e0, a=0x77ff7fab90, ret=0x0) at C:/msys64/mingw64/include/QtCore/qobjectdefs_impl.h:418
#11 0x00007fff9597fb5c in void doActivate<false>(QObject*, int, void**) () from C:\Projects\freeciv21-origin\build\Windows-x86_64\_CPack_Packages\Windows-x86_64\NSIS\Freeciv21-v3.0.313006-Windows-x86_64\freeciv21\qt5core.dll
#12 0x00007fff94602165 in QAbstractButtonPrivate::emitClicked() () from C:\Projects\freeciv21-origin\build\Windows-x86_64\_CPack_Packages\Windows-x86_64\NSIS\Freeciv21-v3.0.313006-Windows-x86_64\freeciv21\qt5widgets.dll
#13 0x00007fff94603df4 in QAbstractButtonPrivate::click() () from C:\Projects\freeciv21-origin\build\Windows-x86_64\_CPack_Packages\Windows-x86_64\NSIS\Freeciv21-v3.0.313006-Windows-x86_64\freeciv21\qt5widgets.dll
#14 0x00007fff94604006 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) () from C:\Projects\freeciv21-origin\build\Windows-x86_64\_CPack_Packages\Windows-x86_64\NSIS\Freeciv21-v3.0.313006-Windows-x86_64\freeciv21\qt5widgets.dll
#15 0x00007fff945566e0 in QWidget::event(QEvent*) () from C:\Projects\freeciv21-origin\build\Windows-x86_64\_CPack_Packages\Windows-x86_64\NSIS\Freeciv21-v3.0.313006-Windows-x86_64\freeciv21\qt5widgets.dll
#16 0x00007fff94517ec3 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from C:\Projects\freeciv21-origin\build\Windows-x86_64\_CPack_Packages\Windows-x86_64\NSIS\Freeciv21-v3.0.313006-Windows-x86_64\freeciv21\qt5widgets.dll
#17 0x00007fff9451f80f in QApplication::notify(QObject*, QEvent*) () from C:\Projects\freeciv21-origin\build\Windows-x86_64\_CPack_Packages\Windows-x86_64\NSIS\Freeciv21-v3.0.313006-Windows-x86_64\freeciv21\qt5widgets.dll
#18 0x00007fff95896968 in QCoreApplication::sendSpontaneousEvent(QObject*, QEvent*) () from C:\Projects\freeciv21-origin\build\Windows-x86_64\_CPack_Packages\Windows-x86_64\NSIS\Freeciv21-v3.0.313006-Windows-x86_64\freeciv21\qt5core.dll
#19 0x00007fff9451e1f7 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () from C:\Projects\freeciv21-origin\build\Windows-x86_64\_CPack_Packages\Windows-x86_64\NSIS\Freeciv21-v3.0.313006-Windows-x86_64\freeciv21\qt5widgets.dll
#20 0x00007fff9456e4f2 in QWidgetWindow::handleMouseEvent(QMouseEvent*) () from C:\Projects\freeciv21-origin\build\Windows-x86_64\_CPack_Packages\Windows-x86_64\NSIS\Freeciv21-v3.0.313006-Windows-x86_64\freeciv21\qt5widgets.dll
#21 0x00007fff94571675 in QWidgetWindow::event(QEvent*) () from C:\Projects\freeciv21-origin\build\Windows-x86_64\_CPack_Packages\Windows-x86_64\NSIS\Freeciv21-v3.0.313006-Windows-x86_64\freeciv21\qt5widgets.dll
#22 0x00007fff94517ec3 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from C:\Projects\freeciv21-origin\build\Windows-x86_64\_CPack_Packages\Windows-x86_64\NSIS\Freeciv21-v3.0.313006-Windows-x86_64\freeciv21\qt5widgets.dll
#23 0x00007fff95896968 in QCoreApplication::sendSpontaneousEvent(QObject*, QEvent*) () from C:\Projects\freeciv21-origin\build\Windows-x86_64\_CPack_Packages\Windows-x86_64\NSIS\Freeciv21-v3.0.313006-Windows-x86_64\freeciv21\qt5core.dll
#24 0x00007fff94b21440 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from C:\Projects\freeciv21-origin\build\Windows-x86_64\_CPack_Packages\Windows-x86_64\NSIS\Freeciv21-v3.0.313006-Windows-x86_64\freeciv21\qt5gui.dll
#25 0x00007fff94afb4ec in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from C:\Projects\freeciv21-origin\build\Windows-x86_64\_CPack_Packages\Windows-x86_64\NSIS\Freeciv21-v3.0.313006-Windows-x86_64\freeciv21\qt5gui.dll
#26 0x00007fff958f1a80 in QEventDispatcherWin32::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from C:\Projects\freeciv21-origin\build\Windows-x86_64\_CPack_Packages\Windows-x86_64\NSIS\Freeciv21-v3.0.313006-Windows-x86_64\freeciv21\qt5core.dll
#27 0x00007fffae840de5 in QWindowsGuiEventDispatcher::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from C:\Projects\freeciv21-origin\build\Windows-x86_64\_CPack_Packages\Windows-x86_64\NSIS\Freeciv21-v3.0.313006-Windows-x86_64\freeciv21\platforms\qwindows.dll
#28 0x00007fff95894b73 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from C:\Projects\freeciv21-origin\build\Windows-x86_64\_CPack_Packages\Windows-x86_64\NSIS\Freeciv21-v3.0.313006-Windows-x86_64\freeciv21\qt5core.dll
#29 0x00007fff9589d677 in QCoreApplication::exec() () from C:\Projects\freeciv21-origin\build\Windows-x86_64\_CPack_Packages\Windows-x86_64\NSIS\Freeciv21-v3.0.313006-Windows-x86_64\freeciv21\qt5core.dll
#30 0x00007ff6dce6fe9c in fc_client::fc_main (this=0x2021ac7e450, qapp=0x77ff7fee20) at C:/Projects/freeciv21-origin/client/fc_client.cpp:155
#31 0x00007ff6dce7edea in ui_main () at C:/Projects/freeciv21-origin/client/gui_main.cpp:98
#32 0x00007ff6dce374af in client_main (argc=3, argv=0x2021ac64af0) at C:/Projects/freeciv21-origin/client/client_main.cpp:611
#33 0x00007ff6dce7ec3b in main (argc=3, argv=0x2021ac64af0) at C:/Projects/freeciv21-origin/client/gui_main.cpp:62
```

**Comment by lmoureaux** [comment]
Reproduced.
