### ISSUE TITLE
Using the "delayed goto" while in city view causes the client to crash

### ISSUE THREAD

**Issue by daavko** [longturn/freeciv21#1125]
**Describe the bug**
Under a specific set of conditions, using the "delayed goto" function, while having a unit selected, while in city view, causes a fatal assertion failure and the client crashes.

**To Reproduce**
1. Create a city
2. Have a unit with multiple moves left outside the city
3. In normal map view, use the "delayed goto" function to plan a 1-tile move for the unit
4. Use the "delayed orders execute" function to execute the 1-tile move
5. With the unit still selected, open a city view
6. Activate the "delayed goto" function
7. Click anywhere on the map
8. Crash!

**Expected behavior**
It shouldn't crash

**Platform and version (please complete the following information):**
 - OS: Windows 10
 - Freeciv21 version: beta 2 and current master (4c6aee6)
 - Ruleset/Longturn game (if applicable): not applicable

**Additional context**
Backtrace from current master:
```
warning: [fatal] freeciv21-client (C:/msys64/mingw64/include/QtCore/qlist.h:571) - ASSERT failure in QList<T>::at: "index out of range", file C:/msys64/mingw64/include/QtCore/qlist.h, line 571
gdb: unknown target exception 0xc0000602 at 0x7ff82afbfa32

Thread 1 received signal ?, Unknown signal.
0x00007ff82afbfa32 in RaiseFailFastException () from C:\WINDOWS\System32\KernelBase.dll
(gdb) bt
#0  0x00007ff82afbfa32 in RaiseFailFastException () from C:\WINDOWS\System32\KernelBase.dll
#1  0x00007fff8c7138d1 in qt_message_fatal(QtMsgType, QMessageLogContext const&, QString const&) [clone .constprop.0]
    ()
   from C:\Projects\freeciv21-origin\build\Windows-x86_64\_CPack_Packages\Windows-x86_64\NSIS\Freeciv21-v3.0.313006-Windows-x86_64\freeciv21\qt5core.dll
#2  0x00007fff8ca28e52 in QMessageLogger::fatal(char const*, ...) const ()
   from C:\Projects\freeciv21-origin\build\Windows-x86_64\_CPack_Packages\Windows-x86_64\NSIS\Freeciv21-v3.0.313006-Windows-x86_64\freeciv21\qt5core.dll
#3  0x00007fff8ca28977 in qt_assert_x(char const*, char const*, char const*, int) ()
   from C:\Projects\freeciv21-origin\build\Windows-x86_64\_CPack_Packages\Windows-x86_64\NSIS\Freeciv21-v3.0.313006-Windows-x86_64\freeciv21\qt5core.dll
#4  0x00007ff72c8097e0 in QList<qfc_delayed_unit_item*>::at (this=0x1e4b6aa9908, i=-1)
    at C:/msys64/mingw64/include/QtCore/qlist.h:571
#5  0x00007ff72c4c110c in mr_menu::set_tile_for_order (this=0x1e4b6aa9870, ptile=0x1e4bcf34200)
    at C:/Projects/freeciv21-origin/client/menu.cpp:1271
#6  0x00007ff72c49df8b in map_view::shortcut_pressed (this=0x1e4b7346d60, key=0)
    at C:/Projects/freeciv21-origin/client/mapctrl.cpp:264
#7  0x00007ff72c49f1e6 in map_view::mousePressEvent (this=0x1e4b7346d60, event=0x3294ffb4a0)
    at C:/Projects/freeciv21-origin/client/mapctrl.cpp:454
#8  0x00007fff8bad66e0 in QWidget::event(QEvent*) ()
   from C:\Projects\freeciv21-origin\build\Windows-x86_64\_CPack_Packages\Windows-x86_64\NSIS\Freeciv21-v3.0.313006-Windows-x86_64\freeciv21\qt5widgets.dll
#9  0x00007fff8ba97ec3 in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from C:\Projects\freeciv21-origin\build\Windows-x86_64\_CPack_Packages\Windows-x86_64\NSIS\Freeciv21-v3.0.313006-Windows-x86_64\freeciv21\qt5widgets.dll
#10 0x00007fff8ba9f80f in QApplication::notify(QObject*, QEvent*) ()
   from C:\Projects\freeciv21-origin\build\Windows-x86_64\_CPack_Packages\Windows-x86_64\NSIS\Freeciv21-v3.0.313006-Windows-x86_64\freeciv21\qt5widgets.dll
#11 0x00007fff8c8e6968 in QCoreApplication::sendSpontaneousEvent(QObject*, QEvent*) ()
   from C:\Projects\freeciv21-origin\build\Windows-x86_64\_CPack_Packages\Windows-x86_64\NSIS\Freeciv21-v3.0.313006-Windows-x86_64\freeciv21\qt5core.dll
#12 0x00007fff8ba9e1f7 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) ()
   from C:\Projects\freeciv21-origin\build\Windows-x86_64\_CPack_Packages\Windows-x86_64\NSIS\Freeciv21-v3.0.313006-Windows-x86_64\freeciv21\qt5widgets.dll
#13 0x00007fff8baee4f2 in QWidgetWindow::handleMouseEvent(QMouseEvent*) ()
   from C:\Projects\freeciv21-origin\build\Windows-x86_64\_CPack_Packages\Windows-x86_64\NSIS\Freeciv21-v3.0.313006-Windows-x86_64\freeciv21\qt5widgets.dll
#14 0x00007fff8baf1675 in QWidgetWindow::event(QEvent*) ()
   from C:\Projects\freeciv21-origin\build\Windows-x86_64\_CPack_Packages\Windows-x86_64\NSIS\Freeciv21-v3.0.313006-Windows-x86_64\freeciv21\qt5widgets.dll
#15 0x00007fff8ba97ec3 in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from C:\Projects\freeciv21-origin\build\Windows-x86_64\_CPack_Packages\Windows-x86_64\NSIS\Freeciv21-v3.0.313006-Windows-x86_64\freeciv21\qt5widgets.dll
#16 0x00007fff8c8e6968 in QCoreApplication::sendSpontaneousEvent(QObject*, QEvent*) ()
   from C:\Projects\freeciv21-origin\build\Windows-x86_64\_CPack_Packages\Windows-x86_64\NSIS\Freeciv21-v3.0.313006-Windows-x86_64\freeciv21\qt5core.dll
#17 0x00007fff8c0a1440 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) ()
   from C:\Projects\freeciv21-origin\build\Windows-x86_64\_CPack_Packages\Windows-x86_64\NSIS\Freeciv21-v3.0.313006-Windows-x86_64\freeciv21\qt5gui.dll
#18 0x00007fff8c07b4ec in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from C:\Projects\freeciv21-origin\build\Windows-x86_64\_CPack_Packages\Windows-x86_64\NSIS\Freeciv21-v3.0.313006-Windows-x86_64\freeciv21\qt5gui.dll
#19 0x00007fff8c941a80 in QEventDispatcherWin32::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from C:\Projects\freeciv21-origin\build\Windows-x86_64\_CPack_Packages\Windows-x86_64\NSIS\Freeciv21-v3.0.313006-Windows-x86_64\freeciv21\qt5core.dll
#20 0x00007fffabaa0de5 in QWindowsGuiEventDispatcher::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from C:\Projects\freeciv21-origin\build\Windows-x86_64\_CPack_Packages\Windows-x86_64\NSIS\Freeciv21-v3.0.313006-Windows-x86_64\freeciv21\platforms\qwindows.dll
#21 0x00007fff8c8e4b73 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from C:\Projects\freeciv21-origin\build\Windows-x86_64\_CPack_Packages\Windows-x86_64\NSIS\Freeciv21-v3.0.313006-Windows-x86_64\freeciv21\qt5core.dll
#22 0x00007fff8c8ed677 in QCoreApplication::exec() ()
   from C:\Projects\freeciv21-origin\build\Windows-x86_64\_CPack_Packages\Windows-x86_64\NSIS\Freeciv21-v3.0.313006-Windows-x86_64\freeciv21\qt5core.dll
#23 0x00007ff72c46fe9c in fc_client::fc_main (this=0x1e4b3fee450, qapp=0x3294fff3f0)
    at C:/Projects/freeciv21-origin/client/fc_client.cpp:155
#24 0x00007ff72c47edea in ui_main () at C:/Projects/freeciv21-origin/client/gui_main.cpp:98
#25 0x00007ff72c4374af in client_main (argc=3, argv=0x1e4b3fd4af0)
    at C:/Projects/freeciv21-origin/client/client_main.cpp:611
#26 0x00007ff72c47ec3b in main (argc=3, argv=0x1e4b3fd4af0) at C:/Projects/freeciv21-origin/client/gui_main.cpp:62
```

**Comment by jwrober** [comment]
Can reproduce in both msys2 and visual studio
