### ISSUE TITLE
Segfault when doing /take

### ISSUE THREAD

**Issue by lmoureaux** [longturn/freeciv21#1224]
> It's the expected behavior after the fix. Before it, if you had a unit focused, you'd get an assertion.

If I have a unit selected and then `/observe` I get no assertion. If it then do a subsequent `/take` I get a segfault

here is the backtrace

```
Thread 1 "freeciv21-clien" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff6407859 in __GI_abort () at abort.c:79
#2  0x00007ffff647226e in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff659c298 "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#3  0x00007ffff647a2fc in malloc_printerr (str=str@entry=0x7ffff659e690 "double free or corruption (!prev)") at malloc.c:5347
#4  0x00007ffff647bfac in _int_free (av=0x7ffff65d1b80 <main_arena>, p=0x55555a3657a0, have_lock=<optimized out>) at malloc.c:4317
#5  0x000055555587acaf in player_clear(player*, bool) (pplayer=0x55555a603320, full=false) at ../common/player.cpp:632
#6  0x0000555555831828 in game_reset() () at ../common/game.cpp:472
#7  0x0000555555611f0d in client_game_reset() () at ../client/client_main.cpp:294
#8  0x00005555556178df in set_client_state(client_states) (newstate=C_S_PREPARING) at ../client/client_main.cpp:829
#9  0x00005555555cfab5 in handle_conn_info(packet_conn_info const*) (pinfo=0x55555c2428f0) at ../client/packhand.cpp:2773
#10 0x00005555557fffb5 in client_handle_packet(packet_type, void const*) (type=PACKET_CONN_INFO, packet=0x55555c2428f0) at client/packhand_gen.cpp:260
#11 0x00005555556173bc in client_packet_input(void*, int) (packet=0x55555c2428f0, type=115) at ../client/client_main.cpp:697
#12 0x000055555562065c in input_from_server(QTcpSocket*) (sock=0x5555565400a0) at ../client/clinet.cpp:293
#13 0x000055555566078c in fc_client::server_input() (this=0x555555fc5c60) at ../client/fc_client.cpp:301
#14 0x000055555566692b in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (fc_client::*)()>::call(void (fc_client::*)(), fc_client*, void**)
    (f=(void (fc_client::*)(class fc_client * const)) 0x555555660732 <fc_client::server_input()>, o=0x555555fc5c60, arg=0x7fffffffcf10) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:152
#15 0x00005555556667a0 in QtPrivate::FunctionPointer<void (fc_client::*)()>::call<QtPrivate::List<>, void>(void (fc_client::*)(), fc_client*, void**)
    (f=(void (fc_client::*)(class fc_client * const)) 0x555555660732 <fc_client::server_input()>, o=0x555555fc5c60, arg=0x7fffffffcf10) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:185
#16 0x0000555555666497 in QtPrivate::QSlotObject<void (fc_client::*)(), QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*)
    (which=1, this_=0x555556e05190, r=0x555555fc5c60, a=0x7fffffffcf10, ret=0x0) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:414
#17 0x00007ffff6bf7328 in QMetaObject::activate(QObject*, int, int, void**) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#18 0x00007ffff7051854 in  () at /lib/x86_64-linux-gnu/libQt5Network.so.5
#19 0x00007ffff70518ef in  () at /lib/x86_64-linux-gnu/libQt5Network.so.5
#20 0x00007ffff7063e29 in  () at /lib/x86_64-linux-gnu/libQt5Network.so.5
#21 0x00007ffff7a1aa66 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#22 0x00007ffff7a240f0 in QApplication::notify(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#23 0x00007ffff6bcb80a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#24 0x00007ffff6c24095 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#25 0x00007ffff52f317d in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#26 0x00007ffff52f3400 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#27 0x00007ffff52f34a3 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#28 0x00007ffff6c23435 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#29 0x00007ffff6bca3ab in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#30 0x00007ffff6bd2116 in QCoreApplication::exec() () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#31 0x0000555555660120 in fc_client::fc_main(QApplication*) (this=0x555555fc5c60, qapp=0x7fffffffd880) at ../client/fc_client.cpp:155
#32 0x0000555555675036 in ui_main() () at ../client/gui_main.cpp:99
#33 0x0000555555615eac in client_main(int, char**) (argc=1, argv=0x7fffffffdda8) at ../client/client_main.cpp:609
#34 0x0000555555674e5f in main(int, char**) (argc=1, argv=0x7fffffffdda8) at ../client/gui_main.cpp:63
```

_Originally posted by @jwrober in https://github.com/longturn/freeciv21/issues/1202#issuecomment-1207494812_

**Comment by lmoureaux** [comment]
I'm having a hard time reproducing this
