### ISSUE TITLE
Building a city in the tutorial crashes the game

### ISSUE THREAD

**Issue by lmoureaux** [longturn/freeciv21#1473]
**Describe the bug**

As the title says.

**To Reproduce**
1. Start the tutorial
3. Set units to X until your settler gets selected
5. Build a city
7. See crash

**Expected behavior**

Ahem, no crash

**Screenshots**

```
#0  0x00007ffff7727606 in QLabel::setText(QString const&) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#1  0x00005555555fb37c in city_info::update_labels(city*) (this=0x555556f6e770, pcity=0x5555570279f0) at /home/louis/freeciv/freeciv21/client/citydlg.cpp:1078
#2  0x00005555556032b3 in city_dialog::update_info_label() (this=0x555556676230) at /home/louis/freeciv/freeciv21/client/citydlg.cpp:2146
#3  0x0000555555602928 in city_dialog::refresh() (this=0x555556676230) at /home/louis/freeciv/freeciv21/client/citydlg.cpp:2026
#4  0x0000555555603331 in city_dialog::setup_ui(city*) (this=0x555556676230, qcity=0x5555570279f0) at /home/louis/freeciv/freeciv21/client/citydlg.cpp:2158
#5  0x0000555555605ff6 in real_city_dialog_popup(city*) (pcity=0x5555570279f0) at /home/louis/freeciv/freeciv21/client/citydlg.cpp:2717
#6  0x00005555557f99d5 in cities_update_callback(void*) (data=0x0) at /home/louis/freeciv/freeciv21/client/update_queue.cpp:299
#7  0x00005555557f922c in update_queue::update_unqueue() (this=0x555555f4e2f0) at /home/louis/freeciv/freeciv21/client/update_queue.cpp:127
#8  0x00005555557f92b5 in update_queue::push(waiting_queue_data const&) (this=0x555555f4e2f0, wq=...) at /home/louis/freeciv/freeciv21/client/update_queue.cpp:141
#9  0x00005555557f9306 in update_queue::add(void (*)(void*)) (this=0x555555f4e2f0, callback=0x5555557f9869 <cities_update_callback(void*)>)
    at /home/louis/freeciv/freeciv21/client/update_queue.cpp:149
#10 0x00005555557f9ad7 in popup_city_dialog(city*) (pcity=0x5555570279f0) at /home/louis/freeciv/freeciv21/client/update_queue.cpp:319
#11 0x000055555573675f in city_packet_common(city*, tile*, player*, tile_list*, bool, bool, bool)
--Type <RET> for more, q to quit, c to continue without paging--
    (pcity=0x5555570279f0, pcenter=0x55555cfe1be0, powner=0x55555cf2df70, worked_tiles=0x0, is_new=true, popup=true, investigate=false)
    at /home/louis/freeciv/freeciv21/client/packhand.cpp:1005
#12 0x0000555555735f27 in handle_city_info(packet_city_info const*) (packet=0x55555d3a9260) at /home/louis/freeciv/freeciv21/client/packhand.cpp:866
#13 0x000055555580409a in client_handle_packet(packet_type, void const*) (type=PACKET_CITY_INFO, packet=0x55555d3a9260)
    at /home/louis/freeciv/freeciv21/build/client/packhand_gen.cpp:129
#14 0x0000555555634f8d in client_packet_input(void*, int) (packet=0x55555d3a9260, type=31) at /home/louis/freeciv/freeciv21/client/client_main.cpp:697
#15 0x000055555563de02 in input_from_server(QTcpSocket*) (sock=0x555556667790) at /home/louis/freeciv/freeciv21/client/clinet.cpp:294
#16 0x0000555555680e7c in fc_client::server_input() (this=0x555556166bf0) at /home/louis/freeciv/freeciv21/client/fc_client.cpp:300
```

**Platform and version (please complete the following information):**
 - OS: Linux
 - Freeciv21 version: master
 - Ruleset/Longturn game (if applicable): Tutorial

**Comment by lmoureaux** [comment]
Introduced in #1460
