### ISSUE TITLE
Assertion nation_check(pplayer->nation) failed

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#2195]
**Describe the bug**
Two assertions

`nation.cpp:422 - Assertion nation_check(pplayer->nation) failed`
`nation.cpp:466 - Assertion nullptr != pnation failed`

**To Reproduce**
1. Start a server
2. Connect to network game
3. Take a nation
4. Click disconnect
5. See error

**Expected behavior**
No error

**Screenshots**
N/A

**Platform and version (please complete the following information):**
 - OS: Linux
 - Freeciv21 version: 3.1-alpha.5
 - Ruleset/Longturn game (if applicable): LTT

**Additional context**
Not sure it matters, but came up while testing map gen recipes.

**Comment by blabber** [comment]
The mention of this issue from the LTT-LTX pull request was an mistake. Please ignore, I cant gent remove the reference.

**Comment by lmoureaux** [comment]
Stack trace:
```
#0  fc_assert_handle_failure(char const*, char const*, int, char const*, QString const&)
    (condition=0x555555b1f598 "nation_check(pplayer->nation)", file=0x555555b1eea8 "/home/louis/Personal/freeciv21/common/nation.cpp", line=422, function=0x555555b1f558 "nation_type* nation_of_player(const player*)", message=...) at /home/louis/Personal/freeciv21/utility/log.cpp:224
#1  0x000055555589ae08 in nation_of_player(player const*) (pplayer=0x555559c06aa0) at /home/louis/Personal/freeciv21/common/nation.cpp:422
#2  0x000055555570d679 in pageGame::reloadSidebarIcons() (this=0x5555562caa60) at /home/louis/Personal/freeciv21/client/page_game.cpp:238
#3  0x00005555557fcce4 in update_top_bar_diplomacy_status(bool) (notify=false) at /home/louis/Personal/freeciv21/client/views/view_nations.cpp:1045
#4  0x000055555565a888 in close_all_diplomacy_dialogs() () at /home/louis/Personal/freeciv21/client/diplodlg.cpp:978
#5  0x000055555561e0e2 in set_client_state(client_states) (newstate=C_S_DISCONNECTED) at /home/louis/Personal/freeciv21/client/client_main.cpp:804
#6  0x0000555555625f40 in close_socket_nomessage(connection*) (pc=0x555555c96a60 <client>) at /home/louis/Personal/freeciv21/client/clinet.cpp:61
#7  0x0000555555626e55 in disconnect_from_server() () at /home/louis/Personal/freeciv21/client/clinet.cpp:231
#8  0x00005555556640f4 in fc_client::slot_disconnect() (this=0x555556125db0) at /home/louis/Personal/freeciv21/client/fc_client.cpp:326
```
