### ISSUE TITLE
Crash on middle click

### ISSUE THREAD

**Issue by lmoureaux** [longturn/freeciv21#524]
Encountered in the LTEx24Avi test game:
```
[critical] freeciv21-client (../client/mapview_common.cpp:2661) - Assertion ((ptile_dest_center)->index) >= 0 && ((ptile_dest_center)->index) < MAP_INDEX_SIZE failed
[critical] freeciv21-client (../client/mapview_common.cpp:2661) - Please report this message at https://github.com/longturn/freeciv21/issues
free(): invalid pointer
```

**Comment by lmoureaux** [comment]
Couldn't reproduce after restarting the client.

**Comment by lmoureaux** [comment]
Seemingly related backtrace posted by panch93 on Discord:
```
[critical] freeciv21-client (/home/pranav/freeciv/freeciv21/client/mapview_common.cpp:2661) - Assertion ((ptile_dest_center)->index) >= 0 && ((ptile_dest_center)->index) < MAP_INDEX_SIZE failed
[critical] freeciv21-client (/home/pranav/freeciv/freeciv21/client/mapview_common.cpp:2661) - Please report this message at https://github.com/longturn/freeciv21/issues
free(): invalid pointer

Thread 1 "freeciv21-clien" received signal SIGABRT, Aborted.
0x00007ffff62ddd22 in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff62ddd22 in raise () from /usr/lib/libc.so.6
#1  0x00007ffff62c7862 in abort () from /usr/lib/libc.so.6
#2  0x00007ffff631fd28 in __libc_message () from /usr/lib/libc.so.6
#3  0x00007ffff632792a in malloc_printerr () from /usr/lib/libc.so.6
#4  0x00007ffff6328cfc in _int_free () from /usr/lib/libc.so.6
#5  0x00007ffff632c9e8 in free () from /usr/lib/libc.so.6
#6  0x000055555562b078 in mapdeco_free () at /home/pranav/freeciv/freeciv21/client/mapview_common.cpp:2427
#7  0x000055555562bbee in mapdeco_clear_gotoroutes () at /home/pranav/freeciv/freeciv21/client/mapview_common.cpp:2670
#8  0x000055555572b0b7 in popdown_tile_info () at /home/pranav/freeciv/freeciv21/client/gui-qt/mapview.cpp:727
#9  0x00005555557281b3 in map_view::shortcut_released (this=0x5555573b8530, bt=Qt::MiddleButton) at /home/pranav/freeciv/freeciv21/client/gui-qt/mapctrl.cpp:441
#10 0x000055555572838a in map_view::mouseReleaseEvent (this=0x5555573b8530, event=0x7fffffffca10) at /home/pranav/freeciv/freeciv21/client/gui-qt/mapctrl.cpp:479
#11 0x00007ffff759a0be in QWidget::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#12 0x00007ffff7556d62 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#13 0x00007ffff755eac9 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#14 0x00007ffff6a803aa in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#15 0x00007ffff755d57b in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () from /usr/lib/libQt5Widgets.so.5
#16 0x00007ffff75b3a84 in ?? () from /usr/lib/libQt5Widgets.so.5
#17 0x00007ffff75b6db5 in ?? () from /usr/lib/libQt5Widgets.so.5
#18 0x00007ffff7556d62 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#19 0x00007ffff6a803aa in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#20 0x00007ffff6e5b210 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /usr/lib/libQt5Gui.so.5
#21 0x00007ffff6e307e5 in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Gui.so.5
#22 0x00007ffff2ad0fcc in ?? () from /usr/lib/libQt5XcbQpa.so.5
#23 0x00007ffff546110c in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#24 0x00007ffff54b4b99 in ?? () from /usr/lib/libglib-2.0.so.0
#25 0x00007ffff545e871 in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#26 0x00007ffff6ad8fd6 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#27 0x00007ffff6a7ed1c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#28 0x00007ffff6a87284 in QCoreApplication::exec() () from /usr/lib/libQt5Core.so.5
#29 0x00005555556f84f8 in fc_client::fc_main (this=0x555556553d90, qapp=0x7fffffffd480) at /home/pranav/freeciv/freeciv21/client/gui-qt/fc_client.cpp:155
#30 0x0000555555701a9d in qtg_ui_main () at /home/pranav/freeciv/freeciv21/client/gui-qt/gui_main.cpp:115
#31 0x00005555556000e8 in ui_main () at /home/pranav/freeciv/freeciv21/client/gui_interface.cpp:51
#32 0x00005555555d93ff in client_main (argc=1, argv=0x7fffffffd9a8) at /home/pranav/freeciv/freeciv21/client/client_main.cpp:613
#33 0x00005555557018a7 in main (argc=1, argv=0x7fffffffd9a8) at /home/pranav/freeciv/freeciv21/client/gui-qt/gui_main.cpp:73
```

**Comment by lmoureaux** [comment]
Still happens now and then, but never when I'm running in gdb.

**Comment by lmoureaux** [comment]
Could not reproduce so far. Unless I'm extremely lucky won't be in beta1.

**Comment by lmoureaux** [comment]
The code has changed a lot since the reports and I haven't had this crash in a long time.
