### ISSUE TITLE
Assertion failures in client/options.cpp

### ISSUE THREAD

**Issue by lmoureaux** [longturn/freeciv21#525]
LTEx24Avi
```
[critical] freeciv21-client (../client/options.cpp:2900) - Assertion NULL == psoption->help_text failed
[critical] freeciv21-client (../client/options.cpp:2900) - Please report this message at https://github.com/longturn/freeciv21/issues
```

**Comment by jwrober** [comment]
`[critical] freeciv21-client (../client/options.cpp:601) - Assertion __null != poption failed`

**Comment by lmoureaux** [comment]
Can't find a way to reproduce in a recent build. Is this still present?

**Comment by jwrober** [comment]
Not this one listed above, but I can get 

`[critical] freeciv21-client (../client/options.cpp:573) - Assertion nullptr != poption failed`

**Comment by lmoureaux** [comment]
Can you do the following?
```
$ gdb  build/freeciv21-client
(gdb) break fc_assert_handle_failure <--- This sets a breakpoint in the assert failure handler
(gdb) run
```
And print the stack trace when it breaks.

**Comment by jwrober** [comment]
```
Thread 1 "freeciv21-clien" hit Breakpoint 1, fc_assert_handle_failure (condition=0x7ffff6480156 <__GI___libc_realloc+726> "I\211\305d\213\004%\030", file=0x80 <error: Cannot access memory at address 0x80>, line=21845, 
    function=0x7ffff7ba7ed0 "\363\017\036\372AUATUSH\203\354\030dH\213\004%(", message=...) at ../utility/log.cpp:226
226     {
(gdb) bt
#0  fc_assert_handle_failure(char const*, char const*, int, char const*, QString const&)
    (condition=0x7ffff6480156 <__GI___libc_realloc+726> "I\211\305d\213\004%\030", file=0x80 <error: Cannot access memory at address 0x80>, line=21845, function=0x7ffff7ba7ed0 "\363\017\036\372AUATUSH\203\354\030dH\213\004%(", message=...) at ../utility/log.cpp:226
#1  0x00005555556e1205 in option_get_cb_data(option const*) (poption=0x0) at ../client/options.cpp:573
#2  0x0000555555757534 in get_tileset_list(option const*) (poption=0x0) at ../client/tilespec.cpp:764
#3  0x00005555556c6dc9 in mr_menu::tileset_custom_load() (this=0x555555fb5450) at ../client/menu.cpp:2705
#4  0x00005555556d68a7 in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (mr_menu::*)()>::call(void (mr_menu::*)(), mr_menu*, void**)
    (f=(void (mr_menu::*)(mr_menu * const)) 0x5555556c6a40 <mr_menu::tileset_custom_load()>, o=0x555555fb5450, arg=0x7fffffffc530) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:152
#5  0x00005555556d60db in QtPrivate::FunctionPointer<void (mr_menu::*)()>::call<QtPrivate::List<>, void>(void (mr_menu::*)(), mr_menu*, void**)
    (f=(void (mr_menu::*)(mr_menu * const)) 0x5555556c6a40 <mr_menu::tileset_custom_load()>, o=0x555555fb5450, arg=0x7fffffffc530) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:185
#6  0x00005555556d4daf in QtPrivate::QSlotObject<void (mr_menu::*)(), QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*)
    (which=1, this_=0x55555bf90380, r=0x555555fb5450, a=0x7fffffffc530, ret=0x0) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:414
#7  0x00007ffff6bf7328 in QMetaObject::activate(QObject*, int, int, void**) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007ffff7a143e6 in QAction::triggered(bool) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#9  0x00007ffff7a16aa2 in QAction::activate(QAction::ActionEvent) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#10 0x00007ffff7b9cd12 in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#11 0x00007ffff7ba44ae in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#12 0x00007ffff7ba54d2 in QMenu::mouseReleaseEvent(QMouseEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#13 0x00007ffff7a5d2b6 in QWidget::event(QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#14 0x00007ffff7ba7adb in QMenu::event(QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#15 0x00007ffff7a1aa66 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#16 0x00007ffff7a24343 in QApplication::notify(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#17 0x00007ffff6bcb80a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#18 0x00007ffff7a23457 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#19 0x00007ffff7a79ce4 in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#20 0x00007ffff7a7c1ec in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#21 0x00007ffff7a1aa66 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#22 0x00007ffff7a240f0 in QApplication::notify(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#23 0x00007ffff6bcb80a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#24 0x00007ffff73eb7d3 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#25 0x00007ffff73ed10b in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#26 0x00007ffff73c735b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#27 0x00007ffff1cef32e in  () at /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#28 0x00007ffff52f317d in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#29 0x00007ffff52f3400 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#30 0x00007ffff52f34a3 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#31 0x00007ffff6c23435 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#32 0x00007ffff6bca3ab in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#33 0x00007ffff6bd2116 in QCoreApplication::exec() () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#34 0x0000555555660120 in fc_client::fc_main(QApplication*) (this=0x5555560ffd80, qapp=0x7fffffffd880) at ../client/fc_client.cpp:155
#35 0x0000555555675036 in ui_main() () at ../client/gui_main.cpp:99
#36 0x0000555555615eac in client_main(int, char**) (argc=1, argv=0x7fffffffdda8) at ../client/client_main.cpp:609
#37 0x0000555555674e5f in main(int, char**) (argc=1, argv=0x7fffffffdda8) at ../client/gui_main.cpp:63

```

**Comment by lmoureaux** [comment]
Thanks!
