### ISSUE TITLE
Crash in delete_server_list

### ISSUE THREAD

**Issue by lmoureaux** [longturn/freeciv21#640]
**Describe the bug**

Seen in several different instances. This is an incomplete fix of #636.

**To Reproduce**
1. Make sure the metaserver is not available
2. Start Freeciv21
3. Click on "Connect to network game"
4. Hit "Refresh" several times quickly
5. See crash

**Expected behavior**

Stability.

**Platform and version (please complete the following information):**
 - OS: Linux, Windows 10, Windows 7
 - Freeciv21 version: 3.0-alpha4

**Comment by lmoureaux** [comment]
```
Thread 1 "freeciv21-clien" received signal SIGSEGV, Segmentation fault.
0x00005555557e5bd9 in genlist_head (pgenlist=0x18) at ../utility/genlist.h:105
105       return (NULL != pgenlist ? pgenlist->head_link : NULL);
(gdb) bt
#0  0x00005555557e5bd9 in genlist_head(genlist const*) (pgenlist=0x18) at ../utility/genlist.h:105
#1  0x00005555557e7f29 in delete_server_list(server_list*) (server_list=0x18) at ../client/servers.cpp:474
#2  0x00005555557e82f2 in server_scan_finish(server_scan*) (scan=0x5555575145f0) at ../client/servers.cpp:612
#3  0x000055555577c5c1 in page_network::destroy_server_scans() (this=0x5555572301b0) at ../client/gui-qt/page_network.cpp:288
#4  0x000055555577c6f2 in page_network::update_network_lists() (this=0x5555572301b0) at ../client/gui-qt/page_network.cpp:315
#5  0x000055555577fe5f in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (page_network::*)()>::call(void (page_network::*)(), page_network*, void**)
    (f=(void (page_network::*)(page_network * const)) 0x55555577c6be <page_network::update_network_lists()>, o=0x5555572301b0, arg=0x7fffffffc620)
    at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:152
```
