### ISSUE TITLE
CMA Server SegFault

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#803]
**Describe the bug**
Attached savegame produces a segfault at load due to an issue with CMA

**To Reproduce**
1. Open client and then load a savegame
2. Pick the attached file
3. See segfault

**Expected behavior**
No segfault

**Screenshots**
N/A

**Platform and version (please complete the following information):**
 - OS: Linux
 - Freeciv21 version: HEAD as of 1/3/2022
 - Ruleset/Longturn game (if applicable): Classic

**Additional context**
Here is a `gdb` backtrace
```
hread 1 "freeciv21-clien" received signal SIGSEGV, Segmentation fault.
__GI___libc_free (mem=0x6e006100530020) at malloc.c:3102
3102    malloc.c: No such file or directory.
(gdb) bt
#0  __GI___libc_free (mem=0x6e006100530020) at malloc.c:3102
#1  0x00005555558b39ab in cm_result_destroy(cm_result*) (result=0x555559b4a180) at ../common/aicore/cm.cpp:348
#2  0x0000555555606f00 in cma_yoloswag::result_came_from_server(int)
    (this=0x555555bbb980 <(anonymous namespace)::Q_QGS_gimb::innerFunction()::holder>, last_request_id=10) at ../client/governor.cpp:268
#3  0x0000555555606dba in cma_got_result(int) (citynr=10) at ../client/governor.cpp:218
#4  0x00005555555f23b2 in input_from_server(QTcpSocket*) (sock=0x555556a76ee0) at ../client/clinet.cpp:310
#5  0x000055555571b44a in fc_client::server_input() (this=0x5555568a6340) at ../client/gui-qt/fc_client.cpp:299
#6  0x00005555557213d5 in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (fc_client::*)()>::call(void (fc_client::*)(), fc_client*, void**) (f=(void (fc_client::*)(class fc_client * const)) 0x55555571b3f0 <fc_client::server_input()>, o=0x5555568a6340, arg=0x7fffffffce50)
    at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:152
#7  0x0000555555721277 in QtPrivate::FunctionPointer<void (fc_client::*)()>::call<QtPrivate::List<>, void>(void (fc_client::*)(), fc_client*, void**)
    (f=(void (fc_client::*)(class fc_client * const)) 0x55555571b3f0 <fc_client::server_input()>, o=0x5555568a6340, arg=0x7fffffffce50)
    at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:185
#8  0x0000555555720fff in QtPrivate::QSlotObject<void (fc_client::*)(), QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*)
    (which=1, this_=0x555557281ab0, r=0x5555568a6340, a=0x7fffffffce50, ret=0x0) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:414
#9  0x00007ffff6c1a458 in QMetaObject::activate(QObject*, int, int, void**) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#10 0x00007ffff7d37854 in  () at /lib/x86_64-linux-gnu/libQt5Network.so.5
#11 0x00007ffff7d378ef in  () at /lib/x86_64-linux-gnu/libQt5Network.so.5
#12 0x00007ffff7d49e29 in  () at /lib/x86_64-linux-gnu/libQt5Network.so.5
#13 0x00007ffff7606a66 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#14 0x00007ffff76100f0 in QApplication::notify(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#15 0x00007ffff6bee93a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#16 0x00007ffff6c471c5 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#17 0x00007ffff535017d in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#18 0x00007ffff5350400 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#19 0x00007ffff53504a3 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#20 0x00007ffff6c46565 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#21 0x00007ffff6bed4db in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#22 0x00007ffff6bf5246 in QCoreApplication::exec() () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#23 0x000055555571aeef in fc_client::fc_main(QApplication*) (this=0x5555568a6340, qapp=0x7fffffffd7e0) at ../client/gui-qt/fc_client.cpp:157
#24 0x0000555555724303 in qtg_ui_main() () at ../client/gui-qt/gui_main.cpp:112
#25 0x000055555560a489 in ui_main() () at ../client/gui_interface.cpp:51
#26 0x00005555555e2878 in client_main(int, char**) (argc=1, argv=0x7fffffffdd08) at ../client/client_main.cpp:618
#27 0x0000555555724139 in main(int, char**) (argc=1, argv=0x7fffffffdd08) at ../client/gui-qt/gui_main.cpp:73
```
[freeciv-T0320-Y01872-auto.zip](https://github.com/longturn/freeciv21/files/7804200/freeciv-T0320-Y01872-auto.zip)

**Comment by lmoureaux** [comment]
Reproduced
