### ISSUE TITLE
Client crashes when loading isophex tileset

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#918]
**Describe the bug**
Client crashes when loading isophex tileset

**To Reproduce**
1. Start a new game with Royale rules
2. Click on Game -> Load another tileset
3. Pick isophex
4. Client will lockup

When compiling debug, see backtrace of the error

```
Thread 1 "freeciv21-clien" received signal SIGSEGV, Segmentation fault.
0x0000555555685140 in get_drawable_unit (t=0x55555700b5c8, ptile=0x55555ae22e70) at ../client/tilespec.cpp:5118
5118      if (!unit_is_in_focus(punit) || t->sprites.unit.select[0]
(gdb) bt
#0  0x0000555555685140 in get_drawable_unit(tileset const*, tile const*) (t=0x55555700b5c8, ptile=0x55555ae22e70) at ../client/tilespec.cpp:5118
#1  0x000055555563196b in put_one_tile(QPixmap*, std::unique_ptr<freeciv::layer, std::default_delete<freeciv::layer> > const&, tile*, int, int)
    (pcanvas=0x555557114680, layer=std::unique_ptr<freeciv::layer> = {...}, ptile=0x55555ae22e70, canvas_x=1203, canvas_y=661) at ../client/mapview_common.cpp:1189
#2  0x0000555555633020 in update_map_canvas(int, int, int, int) (canvas_x=0, canvas_y=0, width=2470, height=1088) at ../client/mapview_common.cpp:1384
#3  0x000055555562f894 in base_set_mapview_origin(float, float) (gui_x0=1773, gui_y0=1499) at ../client/mapview_common.cpp:563
#4  0x000055555562fe5b in set_mapview_origin(float, float) (gui_x0=1773, gui_y0=1499) at ../client/mapview_common.cpp:687
#5  0x0000555555630a35 in center_tile_mapcanvas(tile*) (ptile=0x55555ae22e70) at ../client/mapview_common.cpp:863
#6  0x0000555555668af5 in tilespec_reread(char const*, bool) (new_tileset_name=0x55555a9283a8 "isophex", game_fully_initialized=true) at ../client/tilespec.cpp:1166
#7  0x0000555555771e64 in mr_menu::load_new_tileset() (this=0x5555565a7ff0) at ../client/gui-qt/menu.cpp:2811
#8  0x00005555557808cd in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (mr_menu::*)()>::call(void (mr_menu::*)(), mr_menu*, void**)
    (f=(void (mr_menu::*)(mr_menu * const)) 0x555555771db6 <mr_menu::load_new_tileset()>, o=0x5555565a7ff0, arg=0x7fffffffc610) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:152
#9  0x0000555555780225 in QtPrivate::FunctionPointer<void (mr_menu::*)()>::call<QtPrivate::List<>, void>(void (mr_menu::*)(), mr_menu*, void**)
    (f=(void (mr_menu::*)(mr_menu * const)) 0x555555771db6 <mr_menu::load_new_tileset()>, o=0x5555565a7ff0, arg=0x7fffffffc610) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:185
#10 0x000055555577f369 in QtPrivate::QSlotObject<void (mr_menu::*)(), QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*)
    (which=1, this_=0x55555b013f80, r=0x5555565a7ff0, a=0x7fffffffc610, ret=0x0) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:414
#11 0x00007ffff6bbc328 in QMetaObject::activate(QObject*, int, int, void**) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#12 0x00007ffff769f806 in QAbstractButton::clicked(bool) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#13 0x00007ffff769fa2e in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#14 0x00007ffff76a0e73 in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#15 0x00007ffff76a1035 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#16 0x00007ffff75ed2b6 in QWidget::event(QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#17 0x00007ffff75aaa66 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#18 0x00007ffff75b4343 in QApplication::notify(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#19 0x00007ffff6b9080a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#20 0x00007ffff75b3457 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#21 0x00007ffff760935d in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#22 0x00007ffff760c1ec in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#23 0x00007ffff75aaa66 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#24 0x00007ffff75b40f0 in QApplication::notify(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#25 0x00007ffff6b9080a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#26 0x00007ffff6f7b7d3 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
--Type <RET> for more, q to quit, c to continue without paging--
#27 0x00007ffff6f7d10b in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#28 0x00007ffff6f5735b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#29 0x00007ffff235d32e in  () at /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#30 0x00007ffff52f417d in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#31 0x00007ffff52f4400 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#32 0x00007ffff52f44a3 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#33 0x00007ffff6be8435 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#34 0x00007ffff6b8f3ab in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#35 0x00007ffff6b97116 in QCoreApplication::exec() () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#36 0x0000555555724481 in fc_client::fc_main(QApplication*) (this=0x5555566adac0, qapp=0x7fffffffd800) at ../client/gui-qt/fc_client.cpp:161
#37 0x000055555572d858 in ui_main() () at ../client/gui-qt/gui_main.cpp:107
#38 0x00005555555e3a49 in client_main(int, char**) (argc=1, argv=0x7fffffffdd28) at ../client/client_main.cpp:616
#39 0x000055555572d68e in main(int, char**) (argc=1, argv=0x7fffffffdd28) at ../client/gui-qt/gui_main.cpp:68
```

**Expected behavior**
No crash happens. If the map topology and tileset are incompatible a warning should come up.

**Screenshots**
N/A

**Platform and version (please complete the following information):**
 - OS: Linux
 - Freeciv21 version: 3.0-alpha10 - master as of 2/19/22
 - Ruleset/Longturn game (if applicable): Royale

**Additional context**
None

**Comment by jwrober** [comment]
Confirmed same error happens on Windows.

**Comment by lmoureaux** [comment]
Could reproduce, happens when a unit is selected and visible.
