### ISSUE TITLE
Assertion failure on /quit

### ISSUE THREAD

**Issue by lmoureaux** [longturn/freeciv21#928]
**Describe the bug**

When quitting the server, I get the following assertion failure:
```
[critical] freeciv21-server (/home/louis/freeciv/freeciv21/common/improvement.cpp:838) - T278: Assertion __null != pplayer failed
[critical] freeciv21-server (/home/louis/freeciv/freeciv21/common/improvement.cpp:838) - T278: Please report this message at https://github.com/longturn/freeciv21/issues
```

Save:  [toltecs-T0278-Y01785-interrupted.zip](https://github.com/longturn/freeciv21/files/8165263/toltecs-T0278-Y01785-interrupted.zip)

Backtrace:
```
(gdb) bt
#0  wonder_is_built (pplayer=0x0, pimprove=0x555555d3f590 <improvement_types+19600>) at /home/louis/freeciv/freeciv21/common/improvement.cpp:838
#1  0x00005555557f9652 in great_wonder_is_built (pimprove=0x555555d3f590 <improvement_types+19600>)
    at /home/louis/freeciv/freeciv21/common/improvement.cpp:909
#2  0x00005555558230e9 in num_world_buildings_total (building=0x555555d3f590 <improvement_types+19600>)
    at /home/louis/freeciv/freeciv21/common/requirements.cpp:1242
#3  0x0000555555823537 in is_building_in_range (target_player=0x55555ec61b20, target_city=0x55555f87e050, target_building=0x0, range=REQ_RANGE_WORLD, 
    survives=true, source=0x555555d3f590 <improvement_types+19600>) at /home/louis/freeciv/freeciv21/common/requirements.cpp:1361
#4  0x0000555555829d85 in is_req_active (target_player=0x55555ec61b20, other_player=0x0, target_city=0x55555f87e050, target_building=0x0, target_tile=0x0, 
    target_unit=0x0, target_unittype=0x0, target_output=0x555555b57f20 <output_types>, target_specialist=0x0, target_action=0x0, req=0x5555609aeee0, 
    prob_type=RPT_CERTAIN) at /home/louis/freeciv/freeciv21/common/requirements.cpp:3046
#5  0x000055555582aa54 in are_reqs_active (target_player=0x55555ec61b20, other_player=0x0, target_city=0x55555f87e050, target_building=0x0, target_tile=0x0, 
    target_unit=0x0, target_unittype=0x0, target_output=0x555555b57f20 <output_types>, target_specialist=0x0, target_action=0x0, reqs=0x5555609aecf8, 
    prob_type=RPT_CERTAIN) at /home/louis/freeciv/freeciv21/common/requirements.cpp:3378
#6  0x00005555557e6b19 in get_target_bonus_effects (plist=0x0, target_player=0x55555ec61b20, other_player=0x0, target_city=0x55555f87e050, 
    target_building=0x0, target_tile=0x0, target_unit=0x0, target_unittype=0x0, target_output=0x555555b57f20 <output_types>, target_specialist=0x0, 
    target_action=0x0, effect_type=EFT_OUTPUT_BONUS) at /home/louis/freeciv/freeciv21/common/effects.cpp:631
#7  0x00005555557e6fab in get_city_tile_output_bonus (pcity=0x55555f87e050, ptile=0x0, poutput=0x555555b57f20 <output_types>, effect_type=EFT_OUTPUT_BONUS)
    at /home/louis/freeciv/freeciv21/common/effects.cpp:734
#8  0x00005555557dda4b in get_final_city_output_bonus (pcity=0x55555f87e050, otype=O_FOOD) at /home/louis/freeciv/freeciv21/common/city.cpp:2158
#9  0x00005555557ddf91 in set_city_bonuses (pcity=0x55555f87e050) at /home/louis/freeciv/freeciv21/common/city.cpp:2306
#10 0x00005555557dff6a in city_refresh_from_main_map (pcity=0x55555f87e050, workers_map=0x0) at /home/louis/freeciv/freeciv21/common/city.cpp:3068
#11 0x00005555555f2ae9 in city_refresh (pcity=0x55555f87e050) at /home/louis/freeciv/freeciv21/server/cityturn.cpp:165
#12 0x00005555555f2d9e in city_refresh_queue_processing () at /home/louis/freeciv/freeciv21/server/cityturn.cpp:222
#13 0x0000555555629f4d in server_remove_player (pplayer=0x55555ee6ea80) at /home/louis/freeciv/freeciv21/server/plrhand.cpp:1814
#14 0x000055555559a38e in server_game_free () at /home/louis/freeciv/freeciv21/server/srv_main.cpp:3188
#15 0x00005555555957dc in server_quit () at /home/louis/freeciv/freeciv21/server/srv_main.cpp:1860
#16 0x000055555557e28e in freeciv::server::~server (this=0x555556568330, __in_chrg=<optimized out>) at /home/louis/freeciv/freeciv21/server/server.cpp:379
#17 0x000055555557e2ca in freeciv::server::~server (this=0x555556568330, __in_chrg=<optimized out>) at /home/louis/freeciv/freeciv21/server/server.cpp:380
#18 0x00007ffff7a20bc7 in QObject::event(QEvent*) () from /usr/lib/libQt5Core.so.5
```

**To Reproduce**
1. Load attached save
2. Do `/quit`

**Expected behavior**
No error

**Comment by lmoureaux** [comment]
Still an issue in current master.
