### ISSUE TITLE
AutoRevision.txt CI update fails at release time

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#955]
**Describe the bug**
The CI to update AutoRevision.txt as part of the packaging of source archive files fails with the following error message:

```
remote: error: GH006: Protected branch update failed for refs/heads/master.        
remote: error: 7 of 7 required status checks are expected. Changes must be made through a pull request.        
To https://github.com/longturn/freeciv21
 ! [remote rejected]       master -> master (protected branch hook declined)
error: failed to push some refs to 'https://github.com/longturn/freeciv21'
Error: Invalid status code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1022:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5) {
  code: 1
}
Error: Invalid status code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1022:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
```

**To Reproduce**
1. Create a new Release and set an updated tag ID
2. Publish the release
3. See error

**Expected behavior**
The CI should be able to update the given file and produce a ZIP and TAR.GZ archive of the code at the referenced tag.

**Screenshots**
N/A

**Platform and version (please complete the following information):**
 - OS: N/A
 - Freeciv21 version: 3.0-beta.1
 - Ruleset/Longturn game (if applicable): N/A

**Additional context**
None

**Comment by jwrober** [comment]
Found this closed issue - https://github.com/stefanzweifel/git-auto-commit-action/issues/87. To get around this issue it looks like we need an org-bot account to set a personal access token on and then enable force pushes in the repo.
