### ISSUE TITLE
Freeze when setting governor to "Max Food"

### ISSUE THREAD

**Issue by lmoureaux** [longturn/freeciv21#99]
Select all cities in the attached save and set them to "Max Food". Client freezes in `QTcpSocket::waitForReadyRead`. Frozen stack trace:
```
#4  0x00007fe6ba543c52 in QAbstractSocket::waitForReadyRead(int) () from /usr/lib/libQt5Network.so.5
#5  0x000055775668a2b2 in read_from_connection(connection*, bool) [clone .constprop.0] ()
#6  0x000055775668ad9a in input_from_server_till_request_got_processed(QTcpSocket*, int) ()
#7  0x00005577567eb0cf in wait_for_requests(char const*, int, int) ()
#8  0x00005577567ec6f0 in apply_result_on_server(city*, cm_result const*) ()
#9  0x00005577567ece43 in handle_city(city*) ()
#10 0x00005577567e8797 in call_handle_methods() [clone .part.0] ()
#11 0x00005577567ed52f in cma_put_city_under_agent(city*, cm_parameter const*) ()
#12 0x0000557756711c5a in city_widget::display_list_menu(QPoint)::{lambda(QAction*)#1}::operator()(QAction*) const ()
```
[bug.sav.gz](https://github.com/longturn/freeciv21/files/5576819/bug.sav.gz)

**Comment by mir3x** [comment]
Favourite error with sockets is back
It was working here fc23f6a09731e66c0270396c36735bd097c84f9c.
Here stopped working 47e31328ec77f8b16a65dab7f4f75bf7e84628e3

**Comment by mir3x** [comment]
there is fake fix :D https://github.com/mir3x/freeciv21/commit/3913d398b6a0fd597734ab70b86e7edcc1d975e6
